[package]
name = "window_rs_learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"

[dependencies.windows]
version = "0.56.0"
features = [
    "Win32_Graphics_DirectWrite",
]